"""Daily report generation that combines analysis output with the LLM client."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import cast

from loguru import logger

from src.llm.client import LLMClient
from src.llm.prompts import build_daily_report_prompt
from src.llm.report_period import (
    ReportPeriod,
    normalize_report_period,
    report_period_label,
    report_period_scope,
    select_report_period,
)
from src.reporting import (
    ReportAuditLog,
    ReportEvidence,
    ReportVerifier,
    VerificationResult,
    append_quality_notes,
    build_report_evidence,
)


REPORT_MAX_TOKENS = 1024


class ReportGenerator:
    """Generate investor-facing daily reports from analysis-engine results."""

    def __init__(
        self,
        llm_client: LLMClient,
        config: object | None = None,
        audit_log: ReportAuditLog | None = None,
    ) -> None:
        self.llm_client: LLMClient = llm_client
        self.config: object | None = config
        self.verifier = ReportVerifier()
        self.audit_log = audit_log if audit_log is not None else ReportAuditLog()

    async def generate_daily_report(
        self,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str | None = None,
    ) -> str:
        """Generate a formatted periodic report.

        The normal path builds prompts and calls the configured LLM. If the LLM
        request fails or returns empty text, a deterministic six-section report is
        generated from the raw analysis data.
        """

        period = normalize_report_period(report_period) if report_period is not None else select_report_period((analysis_result or {}).get("date"))
        label = report_period_label(period)
        logger.info("Building {} prompts", label)
        system_prompt, user_prompt = build_daily_report_prompt(analysis_result, report_period=period)

        try:
            logger.info("Calling LLM for {} generation", label)
            report = await self.llm_client.generate(
                user_prompt,
                system_prompt=system_prompt,
                temperature=0.7,
                max_tokens=min(self.llm_client.max_tokens, REPORT_MAX_TOKENS),
            )
            formatted_report = report.strip()
            if not formatted_report:
                raise ValueError("LLM returned an empty report")
            verified_report = self._verify_report(formatted_report, analysis_result, period, source="llm")
            logger.info("{} generated by LLM, chars={}", label, len(verified_report))
            return verified_report
        except Exception as exc:  # Fallback is intentionally broad for delivery reliability.
            logger.exception("LLM {} generation failed; using fallback report", label)
            fallback = self._build_fallback_report(analysis_result, error=exc, report_period=period)
            fallback = self._verify_report(fallback, analysis_result, period, source="fallback")
            logger.info("Fallback {} generated, chars={}", label, len(fallback))
            return fallback

    def _verify_report(
        self,
        report: str,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str | None,
        source: str,
    ) -> str:
        """Run deterministic quality checks and append concise findings."""

        evidence = build_report_evidence(analysis_result, report_period=report_period)
        result = self.verifier.verify(report, evidence)
        if result.has_findings:
            logger.warning(
                "Report verification findings count={} confidence={:.2f} passed={}",
                len(result.findings),
                result.confidence,
                result.passed,
            )
        verified_report = append_quality_notes(report, result)
        self._write_audit_record(verified_report, evidence, result, source)
        return verified_report

    def _write_audit_record(
        self,
        report: str,
        evidence: ReportEvidence,
        result: VerificationResult,
        source: str,
    ) -> None:
        """Persist report audit data without affecting delivery."""

        try:
            self.audit_log.append(report=report, evidence=evidence, verification=result, source=source)
        except Exception:
            logger.exception("Failed to write report audit record")

    def _build_fallback_report(
        self,
        analysis_result: dict[str, object],
        *,
        error: Exception,
        report_period: ReportPeriod | str | None = None,
    ) -> str:
        result = _as_mapping(analysis_result)
        date = str(result.get("date") or "今日")
        period = normalize_report_period(report_period) if report_period is not None else select_report_period(date)
        label = report_period_label(period)
        scope = report_period_scope(period)
        overview = _as_mapping(result.get("overview"))
        trend = _as_mapping(result.get("trend"))
        opportunities = _as_sequence(result.get("sector_opportunities"))
        valuation = _as_mapping(result.get("valuation"))
        risk_alerts = _as_sequence(result.get("risk_alerts"))
        portfolio = _as_mapping(result.get("portfolio_status"))

        lines = [
            f"📊 {date} 投资{label}",
            "",
            f"一、{scope}概览",
            _overview_text(overview),
            "",
            "二、方向信号",
            _trend_text(trend),
            "",
            "三、板块机会",
            _opportunity_text(opportunities),
            "",
            "四、估值温度",
            _valuation_text(valuation),
            "",
            "五、风险提醒",
            _risk_text(risk_alerts, error),
            "",
            "六、你的持仓",
            _portfolio_text(portfolio),
        ]
        return "\n".join(lines).strip()


def _overview_text(overview: Mapping[str, object]) -> str:
    direction = overview.get("direction") or "观望"
    summary = overview.get("summary") or "暂无完整市场概览数据"
    key_events = _as_sequence(overview.get("key_events"))
    events_text = "；".join(str(event) for event in key_events[:3]) if key_events else "暂无关键事件"
    return f"总体判断：{direction}。{summary}。关键事件：{events_text}。"


def _trend_text(trend: Mapping[str, object]) -> str:
    advice = trend.get("position_advice") or "建议维持均衡仓位"
    ma_alignment = trend.get("ma_alignment") or "暂无均线数据"
    standing_ratio = _format_percent(trend.get("standing_line_ratio"))
    sentiment = trend.get("sentiment") or "暂无情绪数据"
    confidence = trend.get("confidence")
    confidence_text = f"，信号置信度{confidence}" if confidence is not None else ""
    return (
        f"{advice}。均线排列（短中长期均线的相对位置）为{ma_alignment}，"
        f"站线比例（站上长期均线的ETF占比）为{standing_ratio}，情绪为{sentiment}{confidence_text}。"
    )


def _opportunity_text(opportunities: Sequence[object]) -> str:
    if not opportunities:
        return "暂无明确机会，ETF操作以观察为主。"

    parts: list[str] = []
    for item in opportunities[:3]:
        opportunity = _as_mapping(item)
        sector = opportunity.get("sector_name") or opportunity.get("name") or "未知板块"
        code = opportunity.get("etf_code") or "暂无代码"
        name = opportunity.get("etf_name") or "暂无名称"
        reason = opportunity.get("reason") or "动量排名靠前"
        parts.append(f"{sector}：关注{name}（{code}），{reason}")
    return "；".join(parts) + "。"


def _valuation_text(valuation: Mapping[str, object]) -> str:
    level = valuation.get("overall_level") or "暂无估值判断"
    percentile = _format_percent(valuation.get("pe_percentile"))
    continue_sip = valuation.get("continue_sip")
    sip_text = "继续定投" if continue_sip is True else "暂停新增定投" if continue_sip is False else "等待更多数据"
    alerts = _as_sequence(valuation.get("etf_premium_alerts"))
    alert_text = f"；折溢价提醒{len(alerts)}项" if alerts else ""
    return f"当前估值：{level}。PE分位数（当前估值在历史中的位置）为{percentile}，建议{sip_text}{alert_text}。"


def _risk_text(risk_alerts: Sequence[object], error: Exception) -> str:
    if not risk_alerts:
        return f"暂无新增风险。LLM生成失败，已切换规则报告；原因：{type(error).__name__}。"

    parts: list[str] = []
    for item in risk_alerts[:3]:
        alert = _as_mapping(item)
        alert_type = alert.get("alert_type") or alert.get("type") or "风险信号"
        message = alert.get("message") or "需要关注"
        parts.append(f"{alert_type}：{message}，建议控制新增仓位")
    return "；".join(parts) + "。"


def _portfolio_text(portfolio: Mapping[str, object]) -> str:
    holdings = _as_sequence(portfolio.get("holdings"))
    total_change = _format_percent(portfolio.get("total_change_pct"))
    profit_loss = portfolio.get("total_profit_loss")
    total_text = f"组合当前收益{total_change}"
    if profit_loss is not None:
        total_text += f"，盈亏{profit_loss}"

    if not holdings:
        return f"{total_text}。暂无持仓明细，维持原配置并等待下一次分析。"

    parts: list[str] = []
    for item in holdings[:3]:
        holding = _as_mapping(item)
        code = holding.get("code") or holding.get("symbol") or "暂无代码"
        name = holding.get("name") or code
        change = _format_percent(holding.get("change_pct"))
        action = holding.get("action") or holding.get("advice") or "继续持有"
        parts.append(f"{name}（{code}）最新涨跌{change}，{action}")
    return f"{total_text}。" + "；".join(parts) + "。"


def _as_mapping(value: object) -> dict[str, object]:
    if value is None:
        return {}
    if isinstance(value, Mapping):
        mapping = cast(Mapping[object, object], value)
        return {str(key): item for key, item in mapping.items()}
    return {}


def _as_sequence(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return list(value)
    return []


def _format_percent(value: object) -> str:
    if not isinstance(value, (int, float, str)):
        return "暂无数据"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "暂无数据"
    if abs(number) <= 1:
        number *= 100
    return f"{number:.2f}%"
