"""Daily report generation that combines analysis output with the LLM client."""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import cast

from loguru import logger

from src.llm.client import LLMClient
from src.llm.prompts import build_daily_report_prompt, build_structured_report_prompt
from src.llm.report_renderer import render_structured_report
from src.llm.report_schema import StructuredReport
from src.llm.report_period import (
    ReportPeriod,
    normalize_report_period,
    report_period_label,
    report_period_scope,
    select_report_period,
)
from src.reporting import (
    ReportAuditLog,
    ReportAuditRecord,
    ReportChangeSummary,
    ReportEvidence,
    ReportEvaluator,
    ReportMemoryContext,
    ReportQualityScore,
    ReportVerifier,
    VerificationResult,
    append_quality_notes,
    build_change_summary,
    build_memory_context,
    build_report_evidence,
)


REPORT_MAX_TOKENS = 1024


@dataclass(frozen=True)
class GeneratedReport:
    """Structured result for observability and UI integrations."""

    text: str
    source: str
    evidence: ReportEvidence
    verification: VerificationResult
    quality_score: ReportQualityScore
    memory_context: ReportMemoryContext
    change_summary: ReportChangeSummary


class ReportGenerator:
    """Generate investor-facing daily reports from analysis-engine results."""

    def __init__(
        self,
        llm_client: LLMClient,
        config: object | None = None,
        audit_log: ReportAuditLog | None = None,
    ) -> None:
        self.llm_client: LLMClient = llm_client
        self.config: object | None = config
        self.verifier = ReportVerifier()
        self.audit_log = audit_log if audit_log is not None else ReportAuditLog()

    async def generate_daily_report(
        self,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str | None = None,
    ) -> str:
        """Generate report text while preserving the historical public API."""

        return (await self.generate_daily_report_bundle(analysis_result, report_period=report_period)).text

    async def generate_daily_report_bundle(
        self,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str | None = None,
    ) -> GeneratedReport:
        """Generate a formatted periodic report.

        The normal path builds prompts and calls the configured LLM. If the LLM
        request fails or returns empty text, a deterministic six-section report is
        generated from the raw analysis data.
        """

        period = normalize_report_period(report_period) if report_period is not None else select_report_period((analysis_result or {}).get("date"))
        label = report_period_label(period)
        logger.info("Building {} prompts", label)
        previous_record = self._load_previous_record(analysis_result, period)
        previous_context = self._build_previous_context(previous_record)
        current_evidence = build_report_evidence(analysis_result, report_period=period)
        change_summary = build_change_summary(current_evidence, previous_record, previous_context)
        system_prompt, user_prompt = build_daily_report_prompt(
            analysis_result,
            report_period=period,
            previous_report_context=previous_context,
            change_summary=change_summary,
        )

        try:
            logger.info("Calling LLM for {} generation", label)
            report = await self.llm_client.generate(
                user_prompt,
                system_prompt=system_prompt,
                temperature=0.7,
                max_tokens=min(self.llm_client.max_tokens, REPORT_MAX_TOKENS),
            )
            formatted_report = report.strip()
            if not formatted_report:
                raise ValueError("LLM returned an empty report")
            bundle = self._finalize_report_bundle(
                formatted_report,
                current_evidence,
                previous_context,
                change_summary,
                source="llm",
            )
            logger.info("{} generated by LLM, chars={}", label, len(bundle.text))
            return bundle
        except Exception as exc:  # Fallback is intentionally broad for delivery reliability.
            logger.exception("LLM {} generation failed; using fallback report", label)
            fallback = self._build_fallback_report(analysis_result, error=exc, report_period=period)
            bundle = self._finalize_report_bundle(
                fallback,
                current_evidence,
                previous_context,
                change_summary,
                source="fallback",
            )
            logger.info("Fallback {} generated, chars={}", label, len(bundle.text))
            return bundle

    async def generate_structured_report_bundle(
        self,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str | None = None,
    ) -> GeneratedReport:
        """Generate a structured JSON report with Pydantic validation.

        Prefer this over ``generate_daily_report_bundle()`` — it produces
        traceable output where every number cites its evidence source.
        Falls back to text-based generation if JSON parsing fails.
        """

        period = normalize_report_period(report_period) if report_period is not None else select_report_period((analysis_result or {}).get("date"))
        label = report_period_label(period)
        logger.info("Building structured {} prompts", label)

        previous_record = self._load_previous_record(analysis_result, period)
        previous_context = self._build_previous_context(previous_record)
        current_evidence = build_report_evidence(analysis_result, report_period=period)
        change_summary = build_change_summary(current_evidence, previous_record, previous_context)

        system_prompt, user_prompt = build_structured_report_prompt(
            analysis_result,
            report_period=period,
            previous_report_context=previous_context,
            change_summary=change_summary,
        )

        try:
            logger.info("Calling LLM for structured {} generation", label)
            json_response = await self.llm_client.generate_json(
                user_prompt,
                system_prompt=system_prompt,
                temperature=0.3,  # Lower temperature for structured output
                max_tokens=min(self.llm_client.max_tokens, REPORT_MAX_TOKENS * 3),
                json_mode=True,
            )

            try:
                structured = StructuredReport.model_validate(json_response)
            except Exception as validation_exc:
                logger.error(
                    "Structured {} validation failed: top_keys={} sample={}",
                    label,
                    sorted(json_response.keys()) if isinstance(json_response, dict) else type(json_response).__name__,
                    _truncate_json(json_response),
                )
                raise validation_exc
            report_text = render_structured_report(structured)

            bundle = self._finalize_report_bundle(
                report_text,
                current_evidence,
                previous_context,
                change_summary,
                source="llm-structured",
            )
            logger.info(
                "Structured {} generated, chars={} sections={} metrics_cited={}",
                label, len(bundle.text),
                len(structured.sections),
                sum(len(s.cited_metrics) for s in structured.sections),
            )
            return bundle

        except Exception as exc:
            logger.exception(
                "Structured {} generation failed; falling back to text mode",
                label,
            )
            # Fall back to original text-based generation
            return await self.generate_daily_report_bundle(
                analysis_result, report_period=period,
            )

    def _finalize_report_bundle(
        self,
        report: str,
        evidence: ReportEvidence,
        memory_context: ReportMemoryContext,
        change_summary: ReportChangeSummary,
        source: str,
    ) -> GeneratedReport:
        """Verify, score, audit, and return a structured report bundle."""

        result = self.verifier.verify(report, evidence, source=source)
        if result.has_findings:
            logger.warning(
                "Report verification findings count={} confidence={:.2f} passed={}",
                len(result.findings),
                result.confidence,
                result.passed,
            )
        verified_report = append_quality_notes(report, result)
        quality_score = ReportEvaluator().evaluate(verified_report, evidence, result)
        self._write_audit_record(verified_report, evidence, result, source)
        return GeneratedReport(
            text=verified_report,
            source=source,
            evidence=evidence,
            verification=result,
            quality_score=quality_score,
            memory_context=memory_context,
            change_summary=change_summary,
        )

    def _write_audit_record(
        self,
        report: str,
        evidence: ReportEvidence,
        result: VerificationResult,
        source: str,
    ) -> None:
        """Persist report audit data without affecting delivery."""

        try:
            self.audit_log.append(report=report, evidence=evidence, verification=result, source=source)
        except Exception:
            logger.exception("Failed to write report audit record")

    def _load_previous_record(
        self,
        analysis_result: dict[str, object],
        report_period: ReportPeriod | str,
    ) -> ReportAuditRecord | None:
        """Load previous audit record without blocking generation."""

        try:
            date = str((analysis_result or {}).get("date") or "")
            records = self.audit_log.read_recent(
                limit=1,
                report_period=normalize_report_period(report_period),
                before_date=date,
            )
            return records[-1] if records else None
        except Exception:
            logger.exception("Failed to load previous report record")
            return None

    def _build_previous_context(self, previous_record: ReportAuditRecord | None) -> ReportMemoryContext:
        """Build previous report context without blocking generation."""

        if previous_record is None:
            return ReportMemoryContext(has_history=False, summary="暂无可用历史报告。")
        try:
            return build_memory_context(previous_record)
        except Exception:
            logger.exception("Failed to build previous report context")
            return ReportMemoryContext(has_history=False, summary="历史报告读取失败。")

    def _build_fallback_report(
        self,
        analysis_result: dict[str, object],
        *,
        error: Exception,
        report_period: ReportPeriod | str | None = None,
    ) -> str:
        result = _as_mapping(analysis_result)
        date = str(result.get("date") or "今日")
        period = normalize_report_period(report_period) if report_period is not None else select_report_period(date)
        label = report_period_label(period)
        scope = report_period_scope(period)
        overview = _as_mapping(result.get("overview"))
        trend = _as_mapping(result.get("trend"))
        opportunities = _as_sequence(result.get("sector_opportunities"))
        valuation = _as_mapping(result.get("valuation"))
        risk_alerts = _as_sequence(result.get("risk_alerts"))
        portfolio = _as_mapping(result.get("portfolio_status"))

        lines = [
            f"📊 {date} 投资{label}",
            "",
            f"一、{scope}概览",
            _overview_text(overview),
            "",
            "二、方向信号",
            _trend_text(trend),
            "",
            "三、板块机会",
            _opportunity_text(opportunities),
            "",
            "四、估值温度",
            _valuation_text(valuation),
            "",
            "五、风险提醒",
            _risk_text(risk_alerts, error),
            "",
            "六、你的持仓",
            _portfolio_text(portfolio),
        ]
        return "\n".join(lines).strip()


def _overview_text(overview: Mapping[str, object]) -> str:
    direction = overview.get("direction") or "观望"
    summary = overview.get("summary") or "暂无完整市场概览数据"
    lines: list[str] = [f"总体判断：{direction}。{summary}。"]

    index_snapshot = overview.get("index_snapshot")
    if isinstance(index_snapshot, list) and index_snapshot:
        idx_parts: list[str] = []
        for idx in index_snapshot:
            if isinstance(idx, Mapping):
                name = idx.get("name") or idx.get("code") or "指数"
                change = idx.get("change_pct")
                if change is not None:
                    idx_parts.append(f"{name}{_format_percent(change)}")
        if idx_parts:
            lines.append("主要指数：" + "，".join(idx_parts) + "。")

    breadth = overview.get("market_breadth")
    if isinstance(breadth, dict) and breadth.get("total"):
        lines.append(f"市场宽度：{breadth.get('total')}个板块中{breadth.get('up')}涨{breadth.get('down')}跌。")

    fund_flow = overview.get("fund_flow_direction")
    if fund_flow == "north_inflow":
        lines.append("北向资金：净流入。")
    elif fund_flow == "north_outflow":
        lines.append("北向资金：净流出。")

    key_events = _as_sequence(overview.get("key_events"))
    if key_events:
        events_text = "；".join(str(event) for event in key_events[:3])
        lines.append(f"关键事件：{events_text}。")
    else:
        lines.append("关键事件：暂无。")
    return "".join(lines)


def _trend_text(trend: Mapping[str, object]) -> str:
    advice = trend.get("position_advice") or "建议维持均衡仓位"
    ma_alignment = trend.get("ma_alignment") or "暂无均线数据"
    standing_ratio = _format_percent(trend.get("standing_line_ratio"))
    sentiment = trend.get("sentiment") or "暂无情绪数据"
    confidence = trend.get("confidence")
    confidence_text = f"，信号置信度{confidence}" if confidence is not None else ""
    return (
        f"{advice}。均线排列（短中长期均线的相对位置）为{ma_alignment}，"
        f"站线比例（站上长期均线的ETF占比）为{standing_ratio}，情绪为{sentiment}{confidence_text}。"
    )


def _opportunity_text(opportunities: Sequence[object]) -> str:
    if not opportunities:
        return "暂无明确机会，ETF操作以观察为主。"

    parts: list[str] = []
    for item in opportunities[:3]:
        opportunity = _as_mapping(item)
        sector = opportunity.get("sector_name") or opportunity.get("name") or "未知板块"
        code = opportunity.get("etf_code") or "暂无代码"
        name = opportunity.get("etf_name") or "暂无名称"
        reason = opportunity.get("reason") or "动量排名靠前"
        parts.append(f"{sector}：关注{name}（{code}），{reason}")
    return "；".join(parts) + "。"


def _valuation_text(valuation: Mapping[str, object]) -> str:
    level = valuation.get("overall_level") or "暂无估值判断"
    percentile = _format_percent(valuation.get("pe_percentile"))
    continue_sip = valuation.get("continue_sip")
    sip_text = "继续定投" if continue_sip is True else "暂停新增定投" if continue_sip is False else "等待更多数据"
    alerts = _as_sequence(valuation.get("etf_premium_alerts"))
    alert_text = f"；折溢价提醒{len(alerts)}项" if alerts else ""
    return f"当前估值：{level}。PE分位数（当前估值在历史中的位置）为{percentile}，建议{sip_text}{alert_text}。"


def _risk_text(risk_alerts: Sequence[object], error: Exception) -> str:
    if not risk_alerts:
        return f"暂无新增风险。LLM生成失败，已切换规则报告；原因：{type(error).__name__}。"

    parts: list[str] = []
    for item in risk_alerts[:3]:
        alert = _as_mapping(item)
        alert_type = alert.get("alert_type") or alert.get("type") or "风险信号"
        message = alert.get("message") or "需要关注"
        parts.append(f"{alert_type}：{message}，建议控制新增仓位")
    return "；".join(parts) + "。"


def _portfolio_text(portfolio: Mapping[str, object]) -> str:
    holdings = _as_sequence(portfolio.get("holdings"))
    total_change = _format_percent(portfolio.get("total_change_pct"))
    profit_loss = portfolio.get("total_profit_loss")
    total_text = f"组合当前收益{total_change}"
    if profit_loss is not None:
        total_text += f"，盈亏{profit_loss}"

    if not holdings:
        return f"{total_text}。暂无持仓明细，维持原配置并等待下一次分析。"

    parts: list[str] = []
    for item in holdings[:3]:
        holding = _as_mapping(item)
        code = holding.get("code") or holding.get("symbol") or "暂无代码"
        name = holding.get("name") or code
        change = _format_percent(holding.get("change_pct"))
        action = holding.get("action") or holding.get("advice") or "继续持有"
        parts.append(f"{name}（{code}）最新涨跌{change}，{action}")
    return f"{total_text}。" + "；".join(parts) + "。"


def _as_mapping(value: object) -> dict[str, object]:
    if value is None:
        return {}
    if isinstance(value, Mapping):
        mapping = cast(Mapping[object, object], value)
        return {str(key): item for key, item in mapping.items()}
    return {}


def _as_sequence(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return list(value)
    return []


def _format_percent(value: object) -> str:
    if not isinstance(value, (int, float, str)):
        return "暂无数据"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "暂无数据"
    if abs(number) <= 1:
        number *= 100
    return f"{number:.2f}%"


def _truncate_json(payload: object, limit: int = 400) -> str:
    """Compact JSON dump truncated to ``limit`` chars for diagnostic logs.

    Surfaces what the LLM actually returned when StructuredReport validation
    fails — usually you can see at a glance whether the root object is a
    KeyMetric, a sections-only fragment, or a partial dict.
    """
    try:
        text = json.dumps(payload, ensure_ascii=False, default=str)
    except (TypeError, ValueError):
        text = repr(payload)
    return text if len(text) <= limit else text[:limit] + f"... (+{len(text) - limit} chars)"
